
###############################################################################################################
## For local testing     #
# npx decap-server       # 
# local_backend: true    #
##########################
#
#
# auth making reference : https://github.com/nuzulul/decap-cms-google-apps-script/tree/main
#
###############################################################################################################
backend:
  name: github
  repo : Tamil-Isai-Kalloori/website
  branch: main  # or whatever your branch is
  site_domain: https://tamilisaikalloori.netlify.app  # your website domain for preview
  base_url: https://tamilisaikalloori.netlify.app # PKCE client.html hostname (just the base domain, no path)
  auth_endpoint: /admin/client.html # PKCE client.html path

media_folder: "static/uploads"
public_folder: "/uploads"


collections:
  - name: "settings"
    label: "Site Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "settings"
        label: "Top Bar Settings"
        file: "data/settings.yaml"
        fields:
          - { label: "Phone Number", name: "phone", widget: "string" }
          - { label: "Email Address", name: "email", widget: "string" }
          - { label: "Working Days", name: "hours_days", widget: "string" }
          - { label: "Working Hours", name: "hours_time", widget: "string" }
